name: 'Sipfront Call Test'
description: 'Triggers a call test on the Sipfront App'
author: 'Sipfront GmbH'

# Define your inputs here.
inputs:
  public_key:
    description: 'Your Sipfront API public key'
    required: true
  secret_key:
    description: 'Your Sipfront API secret key'
    required: true
  name:
    description: 'Your Sipfront test name to trigger'
    required: true
  destination:
    description: 'The destination to call, overriding the test configuration'
    required: false

# Define your outputs here.
outputs:
  session_id:
    description: 'The Sipfront session id used for the test run'

runs:
  using: node20
  main: dist/index.js
