name: 'sipfront-call-test'
description: 'Triggers a call test on the Sipfront App'
author: 'Sipfront GmbH'
branding:
  icon: 'phone-call'
  color: 'blue'

# Define your inputs here.
inputs:
  public_key:
    description: 'Your Sipfront API public key'
    required: true
  secret_key:
    description: 'Your Sipfront API secret key'
    required: true
  name:
    description: 'Your Sipfront test name to trigger'
    required: true
  destination:
    description: 'The destination to call, overriding the test configuration'
    required: false
  sf_environment:
    description: 'Internal parameter for testing this action'
    required: false    

# Define your outputs here.
outputs:
  id:
    description: "ID"
  agentpool_name
    description: "Agent-pool name"
  customer_id
    description: "Customer ID"
  customer_name
    description: "Customer name"
  has_passed:
    description: "Did the test pass?"
  is_failed:
    description: 'Did the test fail?'
  is_finished:
    description: 'Did the test finish?'
  project_id:
    description: 'Project id'
  project_name:
    description: 'Project name'
  result_description:
    description: 'Result description'
  session_id:
    description: 'Session ID'
  session_status:
    description: 'Session status'
  started_at:
    description: 'Started at timestamp'
  status:
    description: 'Status'
  stopped_at:
    description: 'Stopped at timestamp'
  tags:
    description: 'Tags'
  test_id:
    description: 'Test ID'
  test_name:
    description: 'Test name'
  testcase_name:
    description: 'Testcase name'

runs:
  using: node20
  main: dist/index.js
